"use client";
import { useState } from "react";
import { Pencil, X } from "lucide-react";
import type { Affiliate } from "@/lib/affiliate";
import { updateAffiliateAction } from "@/app/(admin)/affiliates/actions";
export function AffiliateProfileEditor({ affiliate }: { affiliate: Affiliate }) {
  const [editing, setEditing] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState("");
  async function submit(data: FormData) { setSaving(true); setError(""); const result = await updateAffiliateAction(affiliate.id, { name: String(data.get("name") ?? ""), phone: String(data.get("phone") ?? ""), channels: String(data.get("channels") ?? "").split(",").map(v => v.trim()).filter(Boolean), paymentInfo: { upi: String(data.get("upi") ?? "") || undefined, accountName: String(data.get("accountName") ?? "") || undefined, bankAccount: String(data.get("bankAccount") ?? "") || undefined, ifsc: String(data.get("ifsc") ?? "") || undefined } }); setSaving(false); if (result?.error) return setError(result.error); setEditing(false); }
  if (!editing) return <button onClick={() => setEditing(true)} className="inline-flex items-center gap-1 text-sm font-medium text-[#315f52]"><Pencil className="h-3.5 w-3.5" /> Edit</button>;
  const field = "mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 outline-none focus:border-[#558476]";
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" onMouseDown={() => setEditing(false)}><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-xl" onMouseDown={e => e.stopPropagation()}><div className="flex justify-between"><h3 className="text-lg font-semibold">Edit affiliate</h3><button onClick={() => setEditing(false)}><X className="h-5 w-5" /></button></div><form action={submit} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Name<input required name="name" defaultValue={affiliate.name} className={field} /></label><label className="text-sm font-medium">Phone<input name="phone" defaultValue={affiliate.phone} className={field} /></label><label className="text-sm font-medium sm:col-span-2">Channels<input name="channels" defaultValue={affiliate.channels.join(", ")} className={field} /></label><label className="text-sm font-medium">UPI ID<input name="upi" defaultValue={affiliate.paymentInfo?.upi} className={field} /></label><label className="text-sm font-medium">Account holder<input name="accountName" defaultValue={affiliate.paymentInfo?.accountName} className={field} /></label><label className="text-sm font-medium">Bank account<input name="bankAccount" defaultValue={affiliate.paymentInfo?.bankAccount} className={field} /></label><label className="text-sm font-medium">IFSC<input name="ifsc" defaultValue={affiliate.paymentInfo?.ifsc} className={field} /></label>{error && <p className="sm:col-span-2 rounded-lg bg-red-50 p-2 text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setEditing(false)} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button disabled={saving} className="rounded-lg bg-[#12291F] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving…" : "Save changes"}</button></div></form></div></div>;
}
