"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Plus, Trash2 } from "lucide-react";
import type { AffiliateProgram, AffiliateProgramInput } from "@/lib/affiliate";
import { saveAffiliateProgramAction } from "@/app/(admin)/affiliates/actions";
import { AffiliateInfoTip } from "./AffiliateInfoTip";

type CType=AffiliateProgram["commissionType"];
const field="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-[#558476] focus:ring-2 focus:ring-[#558476]/10";
const box="rounded-xl border border-slate-100 bg-white p-5";
function Help({children,text}:{children:React.ReactNode;text:string}){return <span className="inline-flex items-center gap-1.5">{children}<AffiliateInfoTip text={text}/></span>}

export function ProgramForm({program,products=[]}:{program?:AffiliateProgram;products?:{id:string;name:string}[]}){
 const baseCondition=program?.tierBasis==='order_count'?1:0;
 const savedLevels=[...(program?.tiers??[])].sort((a,b)=>a.minOrderAmount-b.minOrderAmount);
 const savedBase=savedLevels.find(level=>level.minOrderAmount===baseCondition);
 const initialLevels=[{minOrderAmount:baseCondition,rate:savedBase?.rate??program?.defaultRate??10},...savedLevels.filter(level=>level.minOrderAmount!==baseCondition)];
 const router=useRouter(),[tiers,setTiers]=useState(initialLevels),[type,setType]=useState<CType>(program?.commissionType??"percent_of_sale"),[tierBasis,setTierBasis]=useState(program?.tierBasis??"order_value");
 const [productRules,setProductRules]=useState(program?.specialProductCommissions??[]),[excluded,setExcluded]=useState(program?.excludedProductIds??[]);
 const [advanced,setAdvanced]=useState(program?.advancedCommissions??{newCustomer:{enabled:false,rate:0},lifetime:{enabled:false,rate:0},specialCoupon:{enabled:false,rate:0,couponCode:""}}),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const percent=type==="percent_of_sale", unit=percent?"%":"₹";
 async function submit(data:FormData){setSaving(true);setError("");const firstLevel=tiers[0]??{minOrderAmount:tierBasis==='order_count'?1:0,rate:0};const input:AffiliateProgramInput={name:String(data.get("name")),description:String(data.get("description")||""),isActive:data.get("isActive")==="on",isDefault:data.get("isDefault")==="on",commissionType:type,tierBasis,defaultRate:firstLevel.rate,commissionBase:"subtotal",tiers,specialProductCommissions:productRules.filter(r=>r.productId),excludedProductIds:excluded,excludeProductTax:true,excludeShipping:true,advancedCommissions:advanced,attributionWindowDays:Number(data.get("attributionWindowDays")),autoApproveAfterDays:Number(data.get("autoApproveAfterDays")),minPayoutAmount:Number(data.get("minPayoutAmount"))};const result=await saveAffiliateProgramAction(program?._id??null,input);setSaving(false);if(result.error)return setError(result.error);router.push("/affiliates/programs");router.refresh()}
 return <form action={submit} className="grid gap-5 xl:grid-cols-[1fr_340px]"><div className="space-y-5">
  <section className={box}><h3 className="font-semibold">General information</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Program name<input required name="name" defaultValue={program?.name} className={field}/></label><div className="flex items-end gap-5 pb-2"><label className="flex gap-2 text-sm"><input type="checkbox" name="isActive" defaultChecked={program?.isActive??true}/>Active <AffiliateInfoTip text="Inactive programs remain saved but cannot be assigned for new activity."/></label><label className="flex gap-2 text-sm"><input type="checkbox" name="isDefault" defaultChecked={program?.isDefault}/>Default <AffiliateInfoTip text="Automatically assigned to new affiliates unless another program is selected."/></label></div><label className="text-sm font-medium sm:col-span-2">Description<textarea name="description" rows={3} defaultValue={program?.description} className={field}/></label></div></section>
  <section className={box}><h3 className="font-semibold">Default commission</h3><p className="text-sm text-slate-500">Set a base commission that affiliates earn for every eligible referral.</p><div className="mt-5 space-y-4"><label className="block text-sm font-medium"><Help text="Choose whether commission levels are based on the current order value or the affiliate's referred-order count.">Rule</Help><select value={tierBasis} onChange={e=>{const next=e.target.value as 'order_value'|'order_count';setTierBasis(next);setTiers(tiers.map((level,index)=>index===0?{...level,minOrderAmount:next==='order_count'?1:0}:level))}} className={field}><option value="order_value">Advanced — commissions on order values</option><option value="order_count">Advanced — commissions on number of orders</option></select></label><label className="block text-sm font-medium"><Help text="Percent pays a share of product value; per item multiplies by quantity; per order pays once.">Type</Help><select value={type} onChange={e=>setType(e.target.value as CType)} className={field}><option value="percent_of_sale">Percent of sale</option><option value="flat_per_item">Flat rate per item</option><option value="flat_per_order">Flat rate per order</option></select></label></div>
   <div className="mt-7 flex justify-between"><h4 className="inline-flex gap-1 text-sm font-semibold">Level <AffiliateInfoTip text="The highest qualifying level supplies the commission value. Level 1 is the base commission."/></h4><button type="button" onClick={()=>{const highest=Math.max(...tiers.map(t=>t.minOrderAmount));setTiers([...tiers,{minOrderAmount:highest+(tierBasis==='order_count'?1:1000),rate:0}])}} className="inline-flex gap-1 text-sm font-medium text-[#315f52]"><Plus className="h-4 w-4"/>Add new level</button></div><div className="mt-3 space-y-3">{tiers.map((t,i)=><div key={i} className="rounded-lg border bg-slate-50"><div className="flex items-center justify-between border-b px-4 py-2"><b className="text-sm">Level {i+1}</b>{i>0&&<button type="button" aria-label="Delete level" onClick={()=>setTiers(tiers.filter((_,n)=>n!==i))} className="text-red-500"><Trash2 className="h-4 w-4"/></button>}</div><div className="grid gap-4 p-4 sm:grid-cols-2"><label className="text-sm font-medium"><Help text={tierBasis==='order_value'?"Minimum eligible product value for this commission level.":"Referral number from which this commission level starts."}>{tierBasis==='order_value'?'Order value condition':'Order number condition'}</Help><div className="relative"><input type="number" min={tierBasis==='order_count'?1:0} step={tierBasis==='order_count'?1:.01} readOnly={i===0} value={t.minOrderAmount} onChange={e=>setTiers(tiers.map((x,n)=>n===i?{...x,minOrderAmount:+e.target.value}:x))} className={`${field} ${i===0?'bg-slate-100':''}`}/><span className="absolute right-3 top-3 text-slate-500">{tierBasis==='order_value'?'₹':'#'}</span></div></label><label className="text-sm font-medium"><Help text="Commission paid when this level qualifies.">Commission value</Help><div className="relative"><input type="number" min="0" max={percent?100:undefined} step=".01" value={t.rate} onChange={e=>setTiers(tiers.map((x,n)=>n===i?{...x,rate:+e.target.value}:x))} className={field}/><span className="absolute right-3 top-3 text-slate-500">{unit}</span></div></label></div></div>)}</div>
  </section>
  <section className={box}><h3 className="inline-flex gap-1 font-semibold">Special product commission <AffiliateInfoTip text="Matching products use their own value. This overrides the default and levels for those products."/></h3><p className="text-sm text-slate-500">Set a different commission for selected products.</p><div className="mt-4 space-y-3">{productRules.map((r,i)=><div key={i} className="grid grid-cols-[1fr_150px_auto] items-end gap-3"><label className="text-xs font-medium">Product<select value={r.productId} onChange={e=>setProductRules(productRules.map((x,n)=>n===i?{...x,productId:e.target.value}:x))} className={field}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-xs font-medium">Commission ({unit})<input type="number" min="0" max={percent?100:undefined} step=".01" value={r.rate} onChange={e=>setProductRules(productRules.map((x,n)=>n===i?{...x,rate:+e.target.value}:x))} className={field}/></label><button type="button" aria-label="Delete product rule" onClick={()=>setProductRules(productRules.filter((_,n)=>n!==i))} className="mb-2 text-red-500"><Trash2 className="h-4 w-4"/></button></div>)}<button type="button" onClick={()=>setProductRules([...productRules,{productId:"",rate:0}])} className="inline-flex gap-1 text-sm font-medium text-[#315f52]"><Plus className="h-4 w-4"/>Add product rate</button></div></section>
  <section className={box}><h3 className="inline-flex gap-1 font-semibold">Exclusions <AffiliateInfoTip text="Excluded products never generate commission."/></h3><p className="mt-1 text-sm text-slate-500">Shipping and product tax are always excluded from affiliate commission.</p><div className="mt-4"><p className="text-sm font-medium">Products that never earn commission</p><div className="mt-2 max-h-48 space-y-1 overflow-y-auto rounded-lg border p-2">{products.map(p=><label key={p.id} className="flex cursor-pointer items-center gap-2 rounded px-2 py-2 text-sm hover:bg-slate-50"><input type="checkbox" checked={excluded.includes(p.id)} onChange={e=>setExcluded(e.target.checked?[...excluded,p.id]:excluded.filter(id=>id!==p.id))}/>{p.name}</label>)}{!products.length&&<p className="p-2 text-sm text-slate-400">No products available.</p>}</div></div></section>
  <section className={box}><h3 className="inline-flex gap-1 font-semibold">Advanced commission <AffiliateInfoTip text="Overrides the whole eligible order. Priority: special coupon, new customer, lifetime."/></h3><p className="text-sm text-slate-500">Use different values when specific conditions are met.</p><div className="mt-4 space-y-3">{([['newCustomer','New customer'],['lifetime','Lifetime customer'],['specialCoupon','Special coupon']] as const).map(([key,label])=><div key={key} className="grid items-center gap-3 rounded-lg border p-3 sm:grid-cols-[1fr_140px_1fr]"><label className="flex gap-2 text-sm font-medium"><input type="checkbox" checked={advanced[key].enabled} onChange={e=>setAdvanced({...advanced,[key]:{...advanced[key],enabled:e.target.checked}})}/>{label}</label><label className="text-xs">Commission ({unit})<input type="number" min="0" max={percent?100:undefined} step=".01" value={advanced[key].rate} onChange={e=>setAdvanced({...advanced,[key]:{...advanced[key],rate:+e.target.value}})} className={field}/></label>{key==="specialCoupon"?<label className="text-xs">Coupon code<input value={advanced.specialCoupon.couponCode??""} onChange={e=>setAdvanced({...advanced,specialCoupon:{...advanced.specialCoupon,couponCode:e.target.value.toUpperCase()}})} className={field}/></label>:<span/>}</div>)}</div></section>
  <section className={box}><h3 className="font-semibold">Attribution and payouts</h3><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium"><Help text="Days after a click during which an order can be attributed.">Attribution window</Help><input required min="1" type="number" name="attributionWindowDays" defaultValue={program?.attributionWindowDays??30} className={field}/></label><label className="text-sm font-medium"><Help text="Delay before commission is eligible for approval.">Approval delay</Help><input required min="0" type="number" name="autoApproveAfterDays" defaultValue={program?.autoApproveAfterDays??7} className={field}/></label><label className="text-sm font-medium"><Help text="Balance required before payout.">Minimum payout (₹)</Help><input required min="0" step=".01" type="number" name="minPayoutAmount" defaultValue={program?.minPayoutAmount??500} className={field}/></label></div></section>
 </div><aside><section className={`${box} sticky top-5`}><h3 className="font-semibold">Rule summary</h3><ul className="mt-4 space-y-2 text-sm text-slate-600"><li>{type.replaceAll('_',' ')}</li><li>{tiers.length} levels</li><li>{productRules.length} product overrides</li><li>{excluded.length} excluded products</li><li>Historical commissions stay unchanged</li></ul>{error&&<p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-600">{error}</p>}<div className="mt-5 grid gap-2"><button disabled={saving} className="rounded-lg bg-[#558476] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#457366] disabled:opacity-50">{saving?"Saving…":program?"Save changes":"Create program"}</button><button type="button" onClick={()=>router.push('/affiliates/programs')} className="rounded-lg border px-4 py-2.5 text-sm">Cancel</button></div></section></aside></form>
}
