"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Plus, Trash2 } from "lucide-react";
import type { AffiliateProgram, AffiliateProgramInput } from "@/lib/affiliate";
import { saveAffiliateProgramAction } from "@/app/(admin)/affiliates/actions";
import { AffiliateInfoTip } from "./AffiliateInfoTip";

type CType=AffiliateProgram["commissionType"];
const field="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-[#558476] focus:ring-2 focus:ring-[#558476]/10";
const box="rounded-xl border border-slate-100 bg-white p-5";
function Help({children,text}:{children:React.ReactNode;text:string}){return <span className="inline-flex items-center gap-1.5">{children}<AffiliateInfoTip text={text}/></span>}

export function ProgramForm({program,products=[]}:{program?:AffiliateProgram;products?:{id:string;name:string}[]}){
 const router=useRouter(),[tiers,setTiers]=useState(program?.tiers??[]),[type,setType]=useState<CType>(program?.commissionType??"percent_of_sale");
 const [productRules,setProductRules]=useState(program?.specialProductCommissions??[]),[excluded,setExcluded]=useState(program?.excludedProductIds??[]);
 const [advanced,setAdvanced]=useState(program?.advancedCommissions??{newCustomer:{enabled:false,rate:0},lifetime:{enabled:false,rate:0},specialCoupon:{enabled:false,rate:0,couponCode:""}}),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const percent=type==="percent_of_sale", unit=percent?"%":"₹";
 async function submit(data:FormData){setSaving(true);setError("");const input:AffiliateProgramInput={name:String(data.get("name")),description:String(data.get("description")||""),isActive:data.get("isActive")==="on",isDefault:data.get("isDefault")==="on",commissionType:type,tierBasis:data.get("tierBasis")==="order_count"?"order_count":"order_value",defaultRate:Number(data.get("defaultRate")),commissionBase:data.get("commissionBase")==="grand_total"?"grand_total":"subtotal",tiers,specialProductCommissions:productRules.filter(r=>r.productId),excludedProductIds:excluded,excludeProductTax:data.get("excludeProductTax")==="on",excludeShipping:data.get("excludeShipping")==="on",advancedCommissions:advanced,attributionWindowDays:Number(data.get("attributionWindowDays")),autoApproveAfterDays:Number(data.get("autoApproveAfterDays")),minPayoutAmount:Number(data.get("minPayoutAmount"))};const result=await saveAffiliateProgramAction(program?._id??null,input);setSaving(false);if(result.error)return setError(result.error);router.push("/affiliates/programs");router.refresh()}
 return <form action={submit} className="grid gap-5 xl:grid-cols-[1fr_340px]"><div className="space-y-5">
  <div className="rounded-xl border border-sky-100 bg-sky-50 p-4 text-sm text-sky-900"><strong>Rule order:</strong> exclusions are applied first. Advanced rules override the eligible order; otherwise product rules apply to matching products and the qualifying level or default rule applies to the rest.</div>
  <section className={box}><h3 className="font-semibold">General information</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Program name<input required name="name" defaultValue={program?.name} className={field}/></label><div className="flex items-end gap-5 pb-2"><label className="flex gap-2 text-sm"><input type="checkbox" name="isActive" defaultChecked={program?.isActive??true}/>Active <AffiliateInfoTip text="Inactive programs remain saved but cannot be assigned for new activity."/></label><label className="flex gap-2 text-sm"><input type="checkbox" name="isDefault" defaultChecked={program?.isDefault}/>Default <AffiliateInfoTip text="Automatically assigned to new affiliates unless another program is selected."/></label></div><label className="text-sm font-medium sm:col-span-2">Description<textarea name="description" rows={3} defaultValue={program?.description} className={field}/></label></div></section>
  <section className={box}><h3 className="font-semibold">Default commission</h3><p className="text-sm text-slate-500">The base rule used when no override matches.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium"><Help text="Percent pays a share of value; per item multiplies by quantity; per order pays once.">Commission type</Help><select value={type} onChange={e=>setType(e.target.value as CType)} className={field}><option value="percent_of_sale">Percent of sale</option><option value="flat_per_item">Flat rate per item</option><option value="flat_per_order">Flat rate per order</option></select></label><label className="text-sm font-medium">Commission value ({unit})<input required type="number" min="0" max={percent?100:undefined} step=".01" name="defaultRate" defaultValue={program?.defaultRate??10} className={field}/></label><label className="text-sm font-medium"><Help text="Subtotal excludes shipping and tax. Grand total can include them unless excluded below.">Order amount source</Help><select name="commissionBase" defaultValue={program?.commissionBase??"subtotal"} className={field}><option value="subtotal">Order subtotal</option><option value="grand_total">Grand total</option></select></label><label className="text-sm font-medium"><Help text="Levels can unlock from this order's value or the affiliate's cumulative referred-order number.">Calculate levels on</Help><select name="tierBasis" defaultValue={program?.tierBasis??"order_value"} className={field}><option value="order_value">Value of order</option><option value="order_count">Number of orders</option></select></label></div>
   <div className="mt-6 flex justify-between"><div><h4 className="inline-flex gap-1 text-sm font-semibold">Commission levels <AffiliateInfoTip text="The highest qualifying level replaces the default value."/></h4><p className="text-xs text-slate-400">Configure progressive commission values.</p></div><button type="button" onClick={()=>setTiers([...tiers,{minOrderAmount:0,rate:0}])} className="inline-flex gap-1 text-sm font-medium text-[#315f52]"><Plus className="h-4 w-4"/>Add level</button></div><div className="mt-3 space-y-3">{tiers.map((t,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] items-end gap-3 rounded-lg bg-slate-50 p-3"><label className="text-xs font-medium">Level condition<input type="number" min="0" step=".01" value={t.minOrderAmount} onChange={e=>setTiers(tiers.map((x,n)=>n===i?{...x,minOrderAmount:+e.target.value}:x))} className={field}/></label><label className="text-xs font-medium">Commission ({unit})<input type="number" min="0" max={percent?100:undefined} step=".01" value={t.rate} onChange={e=>setTiers(tiers.map((x,n)=>n===i?{...x,rate:+e.target.value}:x))} className={field}/></label><button type="button" aria-label="Delete level" onClick={()=>setTiers(tiers.filter((_,n)=>n!==i))} className="mb-2 text-red-500"><Trash2 className="h-4 w-4"/></button></div>)}{!tiers.length&&<p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-400">No levels configured.</p>}</div>
  </section>
  <section className={box}><h3 className="inline-flex gap-1 font-semibold">Special product commission <AffiliateInfoTip text="Matching products use their own value. This overrides the default and levels for those products."/></h3><p className="text-sm text-slate-500">Set a different commission for selected products.</p><div className="mt-4 space-y-3">{productRules.map((r,i)=><div key={i} className="grid grid-cols-[1fr_150px_auto] items-end gap-3"><label className="text-xs font-medium">Product<select value={r.productId} onChange={e=>setProductRules(productRules.map((x,n)=>n===i?{...x,productId:e.target.value}:x))} className={field}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-xs font-medium">Commission ({unit})<input type="number" min="0" max={percent?100:undefined} step=".01" value={r.rate} onChange={e=>setProductRules(productRules.map((x,n)=>n===i?{...x,rate:+e.target.value}:x))} className={field}/></label><button type="button" aria-label="Delete product rule" onClick={()=>setProductRules(productRules.filter((_,n)=>n!==i))} className="mb-2 text-red-500"><Trash2 className="h-4 w-4"/></button></div>)}<button type="button" onClick={()=>setProductRules([...productRules,{productId:"",rate:0}])} className="inline-flex gap-1 text-sm font-medium text-[#315f52]"><Plus className="h-4 w-4"/>Add product rate</button></div></section>
  <section className={box}><h3 className="inline-flex gap-1 font-semibold">Shipping, taxes and exclusions <AffiliateInfoTip text="Excluded products and charges never generate commission."/></h3><div className="mt-4 flex gap-6"><label className="flex gap-2 text-sm"><input type="checkbox" name="excludeProductTax" defaultChecked={program?.excludeProductTax??true}/>Exclude product tax</label><label className="flex gap-2 text-sm"><input type="checkbox" name="excludeShipping" defaultChecked={program?.excludeShipping??true}/>Exclude shipping</label></div><label className="mt-4 block text-sm font-medium">Exclude products<select multiple value={excluded} onChange={e=>setExcluded(Array.from(e.target.selectedOptions,o=>o.value))} className={`${field} min-h-32`}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><span className="text-xs font-normal text-slate-400">Use Ctrl/Cmd to select multiple products.</span></label></section>
  <section className={box}><h3 className="inline-flex gap-1 font-semibold">Advanced commission <AffiliateInfoTip text="Overrides the whole eligible order. Priority: special coupon, new customer, lifetime."/></h3><p className="text-sm text-slate-500">Use different values when specific conditions are met.</p><div className="mt-4 space-y-3">{([['newCustomer','New customer'],['lifetime','Lifetime customer'],['specialCoupon','Special coupon']] as const).map(([key,label])=><div key={key} className="grid items-center gap-3 rounded-lg border p-3 sm:grid-cols-[1fr_140px_1fr]"><label className="flex gap-2 text-sm font-medium"><input type="checkbox" checked={advanced[key].enabled} onChange={e=>setAdvanced({...advanced,[key]:{...advanced[key],enabled:e.target.checked}})}/>{label}</label><label className="text-xs">Commission ({unit})<input type="number" min="0" max={percent?100:undefined} step=".01" value={advanced[key].rate} onChange={e=>setAdvanced({...advanced,[key]:{...advanced[key],rate:+e.target.value}})} className={field}/></label>{key==="specialCoupon"?<label className="text-xs">Coupon code<input value={advanced.specialCoupon.couponCode??""} onChange={e=>setAdvanced({...advanced,specialCoupon:{...advanced.specialCoupon,couponCode:e.target.value.toUpperCase()}})} className={field}/></label>:<span/>}</div>)}</div></section>
  <section className={box}><h3 className="font-semibold">Attribution and payouts</h3><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium"><Help text="Days after a click during which an order can be attributed.">Attribution window</Help><input required min="1" type="number" name="attributionWindowDays" defaultValue={program?.attributionWindowDays??30} className={field}/></label><label className="text-sm font-medium"><Help text="Delay before commission is eligible for approval.">Approval delay</Help><input required min="0" type="number" name="autoApproveAfterDays" defaultValue={program?.autoApproveAfterDays??7} className={field}/></label><label className="text-sm font-medium"><Help text="Balance required before payout.">Minimum payout (₹)</Help><input required min="0" step=".01" type="number" name="minPayoutAmount" defaultValue={program?.minPayoutAmount??500} className={field}/></label></div></section>
 </div><aside><section className={`${box} sticky top-5`}><h3 className="font-semibold">Rule summary</h3><ul className="mt-4 space-y-2 text-sm text-slate-600"><li>{type.replaceAll('_',' ')}</li><li>{tiers.length} levels</li><li>{productRules.length} product overrides</li><li>{excluded.length} excluded products</li><li>Historical commissions stay unchanged</li></ul>{error&&<p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-600">{error}</p>}<div className="mt-5 grid gap-2"><button disabled={saving} className="rounded-lg bg-[#12291F] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?"Saving…":program?"Save changes":"Create program"}</button><button type="button" onClick={()=>router.push('/affiliates/programs')} className="rounded-lg border px-4 py-2.5 text-sm">Cancel</button></div></section></aside></form>
}
