"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Plus, Trash2 } from "lucide-react";
import type { AffiliateProgram, AffiliateProgramInput } from "@/lib/affiliate";
import { saveAffiliateProgramAction } from "@/app/(admin)/affiliates/actions";

export function ProgramForm({ program }: { program?: AffiliateProgram }) {
  const router=useRouter();
  const [tiers,setTiers]=useState(program?.tiers??[]),[saving,setSaving]=useState(false),[error,setError]=useState("");
  async function submit(data:FormData){setSaving(true);setError("");const input:AffiliateProgramInput={name:String(data.get("name")),description:String(data.get("description")||""),isActive:data.get("isActive")==="on",isDefault:data.get("isDefault")==="on",defaultRate:Number(data.get("defaultRate")),commissionBase:data.get("commissionBase")==="grand_total"?"grand_total":"subtotal",attributionWindowDays:Number(data.get("attributionWindowDays")),minPayoutAmount:Number(data.get("minPayoutAmount")),autoApproveAfterDays:Number(data.get("autoApproveAfterDays")),tiers};const result=await saveAffiliateProgramAction(program?._id??null,input);setSaving(false);if(result.error)return setError(result.error);router.push("/affiliates/programs");router.refresh();}
  const input="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-[#558476] focus:ring-2 focus:ring-[#558476]/10";
  return <form action={submit} className="grid gap-5 xl:grid-cols-[1fr_340px]">
    <div className="space-y-5">
      <section className="rounded-xl border border-slate-100 bg-white p-5"><h3 className="font-semibold">General information</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Program name<input required name="name" defaultValue={program?.name} className={input}/></label><div className="flex items-end gap-5 pb-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isActive" defaultChecked={program?.isActive??true}/>Active</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isDefault" defaultChecked={program?.isDefault}/>Default program</label></div><label className="text-sm font-medium sm:col-span-2">Description<textarea name="description" rows={3} defaultValue={program?.description} className={input}/></label></div></section>
      <section className="rounded-xl border border-slate-100 bg-white p-5"><h3 className="font-semibold">Commission rule</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Commission rate (%)<input required min="0" max="100" step="0.01" type="number" name="defaultRate" defaultValue={program?.defaultRate??10} className={input}/></label><label className="text-sm font-medium">Calculate commission on<select name="commissionBase" defaultValue={program?.commissionBase??"subtotal"} className={input}><option value="subtotal">Order subtotal</option><option value="grand_total">Grand total</option></select></label></div>
        <div className="mt-6 flex items-center justify-between"><div><h4 className="text-sm font-semibold">Commission tiers</h4><p className="text-xs text-slate-400">Higher qualifying thresholds override the base rate.</p></div><button type="button" onClick={()=>setTiers([...tiers,{minOrderAmount:0,rate:0}])} className="inline-flex items-center gap-1 text-sm font-medium text-[#315f52]"><Plus className="h-4 w-4"/>Add tier</button></div>
        <div className="mt-3 space-y-2">{tiers.map((tier,index)=><div key={index} className="grid grid-cols-[1fr_1fr_auto] items-end gap-3 rounded-lg bg-slate-50 p-3"><label className="text-xs font-medium text-slate-500">Minimum order (₹)<input type="number" min="0" value={tier.minOrderAmount} onChange={e=>setTiers(tiers.map((t,i)=>i===index?{...t,minOrderAmount:Number(e.target.value)}:t))} className={input}/></label><label className="text-xs font-medium text-slate-500">Rate (%)<input type="number" min="0" max="100" step="0.01" value={tier.rate} onChange={e=>setTiers(tiers.map((t,i)=>i===index?{...t,rate:Number(e.target.value)}:t))} className={input}/></label><button type="button" onClick={()=>setTiers(tiers.filter((_,i)=>i!==index))} className="mb-1 rounded-lg p-2 text-red-500 hover:bg-red-50"><Trash2 className="h-4 w-4"/></button></div>)}{!tiers.length&&<p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-400">No tiers. The default rate applies to every eligible order.</p>}</div>
      </section>
      <section className="rounded-xl border border-slate-100 bg-white p-5"><h3 className="font-semibold">Attribution and payouts</h3><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium">Attribution window<input required min="1" type="number" name="attributionWindowDays" defaultValue={program?.attributionWindowDays??30} className={input}/><span className="mt-1 block text-xs text-slate-400">Days after click</span></label><label className="text-sm font-medium">Approval delay<input required min="0" type="number" name="autoApproveAfterDays" defaultValue={program?.autoApproveAfterDays??7} className={input}/><span className="mt-1 block text-xs text-slate-400">Days after order</span></label><label className="text-sm font-medium">Minimum payout (₹)<input required min="0" type="number" name="minPayoutAmount" defaultValue={program?.minPayoutAmount??500} className={input}/></label></div></section>
    </div>
    <aside className="space-y-4"><section className="sticky top-5 rounded-xl border border-slate-100 bg-white p-5"><h3 className="font-semibold">Rule summary</h3><ul className="mt-4 space-y-2 text-sm text-slate-600"><li>Percentage-based commission</li><li>{tiers.length} tier{tiers.length===1?"":"s"} configured</li><li>Commission rules are snapshotted per order</li><li>Historical commissions remain unchanged</li></ul>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}<div className="mt-5 grid gap-2"><button disabled={saving} className="rounded-lg bg-[#12291F] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?"Saving…":program?"Save changes":"Create program"}</button><button type="button" onClick={()=>router.push("/affiliates/programs")} className="rounded-lg border px-4 py-2.5 text-sm font-medium">Cancel</button></div></section></aside>
  </form>;
}
