export const Constants = {
  DEFAULT_CURRENCY: 'INR',
  DEFAULT_TIMEZONE: 'Asia/Kolkata',
  WALLET_MIN_BALANCE: 0,
  WALLET_MAX_BALANCE: 100000,
  CART_TTL_DAYS: 30,
  SESSION_TTL_HOURS: 24,
  REFERRAL_CODE_LENGTH: 6,
  ORDER_ID_PREFIX: 'FUL',
  INVOICE_PREFIX: 'INV',
  SUBSCRIPTION_PREFIX: 'SUB',
} as const;
