import Link from "next/link";
import { Plus } from "lucide-react";
import { listAffiliatePrograms } from "@/lib/affiliate";
import { ProgramActions } from "@/components/affiliates/ProgramActions";
import { AffiliateInfoTip } from "@/components/affiliates/AffiliateInfoTip";

export default async function Page(){
 const programs=await listAffiliatePrograms();
 const commission=(p:(typeof programs)[number])=>p.commissionType==="flat_per_item"?`₹${p.defaultRate} per item`:p.commissionType==="flat_per_order"?`₹${p.defaultRate} per order`:`${p.defaultRate}% of ${p.commissionBase.replace("_"," ")}`;
 return <div className="space-y-5">
  <div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Affiliate programs</h2><p className="text-sm text-slate-500">Create a program, configure its rules, then assign affiliates to it.</p></div><Link href="/affiliates/programs/new" className="inline-flex items-center gap-2 rounded-lg bg-[#558476] px-4 py-2 text-sm font-semibold text-white hover:bg-[#457366]"><Plus className="h-4 w-4"/>Create program</Link></div>
  <div className="overflow-x-auto rounded-xl border border-slate-100 bg-white"><table className="w-full text-sm"><thead><tr className="border-b bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><th className="px-5 py-3">Program</th><th className="px-5 py-3"><span className="inline-flex gap-1">Default rule <AffiliateInfoTip text="Used when no advanced or product-specific override matches."/></span></th><th className="px-5 py-3"><span className="inline-flex gap-1">Overrides <AffiliateInfoTip text="Configured level, product, exclusion, and advanced rules."/></span></th><th className="px-5 py-3">Affiliates</th><th className="px-5 py-3"><span className="inline-flex gap-1">Attribution <AffiliateInfoTip text="How long an affiliate click remains eligible for an order."/></span></th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Actions</th></tr></thead><tbody>{programs.map(p=>{const advanced=Object.values(p.advancedCommissions??{}).filter(r=>r.enabled).length;return <tr key={p._id} className="border-b last:border-0"><td className="px-5 py-4"><div className="flex items-center gap-2"><Link href={`/affiliates/programs/${p._id}`} className="font-semibold hover:text-[#315f52] hover:underline">{p.name}</Link>{p.isDefault&&<span className="rounded-full bg-amber-50 px-2 py-0.5 text-[11px] font-medium text-amber-700">Default</span>}</div><p className="mt-1 max-w-sm truncate text-xs text-slate-400">{p.description||"No description"}</p></td><td className="px-5 py-4"><span className="font-semibold">{commission(p)}</span><p className="text-xs text-slate-400">Levels by {p.tierBasis==="order_count"?"order count":"order value"}</p></td><td className="px-5 py-4 text-xs text-slate-600"><p>{p.tiers?.length??0} levels · {p.specialProductCommissions?.length??0} product rates</p><p>{p.excludedProductIds?.length??0} exclusions · {advanced} advanced</p></td><td className="px-5 py-4">{p.affiliateCount??0}</td><td className="px-5 py-4">{p.attributionWindowDays} days</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-xs ${p.isActive?"bg-green-50 text-green-700":"bg-slate-100 text-slate-500"}`}>{p.isActive?"Active":"Inactive"}</span></td><td className="px-5 py-4"><ProgramActions id={p._id} isDefault={p.isDefault}/></td></tr>})}</tbody></table>{!programs.length&&<div className="p-12 text-center"><p className="font-medium">No affiliate programs yet</p><p className="mt-1 text-sm text-slate-400">Create the first program to define how affiliates earn commission.</p></div>}</div>
 </div>
}
